USE [WVGC]
GO
/****** Object:  Table [dbo].[GROWS]    Script Date: 5/21/2026 10:56:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GROWS](
	[Location_ID] [int] NOT NULL,
	[Plant_ID] [int] NULL,
 CONSTRAINT [PK_GROWS] PRIMARY KEY CLUSTERED 
(
	[Location_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PLACES]    Script Date: 5/21/2026 10:56:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PLACES](
	[Places_ID] [int] NOT NULL,
	[Places_Name] [varchar](50) NOT NULL,
	[Access_Level] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Places_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PLANTS]    Script Date: 5/21/2026 10:56:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PLANTS](
	[Plants_ID] [int] NOT NULL,
	[Plant_Name] [varchar](50) NOT NULL,
	[Plant_Status] [varchar](50) NOT NULL,
	[Plant_Type] [varchar](50) NOT NULL,
	[Harvestable] [varchar](50) NOT NULL,
	[Planted_When] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Plants_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[STATUS]    Script Date: 5/21/2026 10:56:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[STATUS](
	[Plants_ID] [int] NOT NULL,
	[Status_Type] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Plants_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PLANTS] ADD  DEFAULT ('Not Yet') FOR [Harvestable]
GO
ALTER TABLE [dbo].[GROWS]  WITH CHECK ADD FOREIGN KEY([Plant_ID])
REFERENCES [dbo].[PLANTS] ([Plants_ID])
GO
ALTER TABLE [dbo].[STATUS]  WITH CHECK ADD FOREIGN KEY([Plants_ID])
REFERENCES [dbo].[PLANTS] ([Plants_ID])
GO
